- name: Add Loki repository
  apt_repository:
   repo: 'deb https://packages.grafana.com/loki/deb stable main'
   state: present
   update_cache: false

- name: Install Loki
  apt:
    name: loki
    state: present

- name: Configure Loki
  copy:
     src: config.yml
     dest: /etc/loki/config.yml
  notify: restart loki
- name: service Loki
  copy:
    src: service.yml
    dest: /etc/systemd/system/service.yml
  notify: restart loki
    
